#!/command/with-contenv /bin/bash

set -x
set -e

mkdir -p /opt/QQ/resources/app/LiteLoader/plugins/NapCat

# 安装 LiteLoader
if [ ! -f "/opt/QQ/resources/app/LiteLoader/package.json" ]; then
    unzip /tmp/LiteLoaderQQNT.zip -d /opt/QQ/resources/app/LiteLoader/
fi

# 安装 NapCat
if [ ! -f "/opt/QQ/resources/app/LiteLoader/plugins/NapCat/manifest.json" ]; then
    unzip /tmp/NapCat.Framework.zip -d /opt/QQ/resources/app/LiteLoader/plugins/NapCat/
fi

# 安装 LiteLoaderQQNT-Kill-Update
if [ ! -f "/opt/QQ/resources/app/LiteLoader/plugins/LiteLoaderQQNT-Kill-Update-0.1.5/manifest.json" ]; then
    unzip /tmp/LiteLoaderQQNT-Kill-Update-0.1.5.zip -d /opt/QQ/resources/app/LiteLoader/plugins/
fi

rm -rf /run/dbus/pid
mkdir -p /var/run/dbus
chmod -R 777 /var/run/dbus
dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address > /var/run/dbus/DBUS_SESSION_BUS_ADDRESS
export DBUS_SESSION_BUS_ADDRESS=$(cat /var/run/dbus/DBUS_SESSION_BUS_ADDRESS)

chmod -R 777 /opt/QQ/
chown -R user /home/user/.config/
chmod -R 777 /home/user/.config/QQ/
