name: push_to_dockerhub

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.arm64
          platforms: linux/arm64
          push: true
          tags: dockerguiimages/docker-ncf:latest-arm64, dockerguiimages/docker-ncf:arm64
      -
        name: Build and push amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.amd64
          platforms: linux/amd64
          push: true
          tags: dockerguiimages/docker-ncf:latest, dockerguiimages/docker-ncf:latest-amd64, dockerguiimages/docker-ncf:amd64
